export const questions = [
  "What embarrasses you the most and/or what’s been your most embarrassing moment?",
  "Who do you look up to the most, and what qualities do you love about that person?",
  "What would be your perfect day? Plan it out from breakfast to bedtime.",
  "What’s your biggest fear?",
  "How do you like to be comforted when you’re sad or upset?",
  "What’s your all-time favorite memory?",
  "What’s your favorite thing you own and why?",
  "Who was the last person who made you cry and why?",
  "Where do you hope to be five years from now? Ten? Fifteen?",
  "If money was no object, what would you buy?",
  "When have you felt the most proud?",
  "When have you felt the most challenged?",
  "Do you have any regrets? If so, what are they?",
  "When was the moment in your life you laughed the hardest?",
  "Which celeb would you want as your other BFF and why?",
  "What did you dream about last night?",
  "Out of all your family members, who are you closest to?",
  "What do you do when no one else is around?",
  "Where do you want to travel the most?",
  "What’s one thing most people don’t know about you?",
  "If you could only eat one thing for the rest of your life, what would it be?",
  "What book has impacted you the most?",
  "If you were going to get some ink, what would you choose and why?",
  "If you had three wishes, what would you wish for?",
  "Do you want to have kids one day? How many?",
  "What's the best present you ever received? Who gave it to you and why was it so special?",
  "If you had to choose only one, would pick a dog or a cat?",
  "Do you believe in aliens?",
  "If you were President, what's the first thing you would work to change in this country?",
  "What college major are you thinking of choosing and why?",
  "If you could only listen to one singer or band for the rest of your life, who would you choose?",
  "You just won $10,000 — what are you going to do with the money?",
  "What's your go-to dish when you have to make dinner?",
  "What's the worst you've ever been physically hurt?",
  "What's your earliest childhood memory?",
  "If you had to live in another time period, what would you choose?",
  "Who was your very first crush?",
  "What foreign language(s) would you want to master and why?",
  "What's your all-time favorite dessert?",
  "If you could change one thing about yourself, what would it be?",
  "What's the luckiest thing that's ever happened to you?",
  "What's your favorite way to exercise?",
  "Do you like roller coasters?",
  "If you had to describe yourself in only three words, what would you choose? What do words do you think your friends ,would choose to describe you?",
  "What's your most embarrassing moment?",
  "Do you believe in soulmates?",
  "What is your most hated chore and why?",
  "What's your favorite holiday and why?",
  "When you can't sleep, what keeps you up at night?",
  "If you were an animal, what would you be?",
  "If you had to create an alter ego for yourself, who would it be and what would you name them?",
  "Do you have any phobias?",
  "What are your top three biggest pet peeves?",
  "What has your hardest goodbye in life been so far?",
  "What would your dream vacay consist of?",
  "If you had to sleep with one person in this room, who would it be",
  "What’s the raunchiest porn you’ve ever watched",
  "What’s the hardest drug you’ve done",
  "What’s the most degrading thing you’ve ever done during sex",
  "Who’s the most inappropriate person you’ve ever fantasied about",
  "What’s the most embarrassing thing you’ve ever done while drunk",
  "What’s the biggest lie you’ve ever told a significant other",
  "How many people in this room would you willingly bang",
  "What’s the most embarrassing item you’ve ever used to get yourself off?",
  "What was the last thing you masturbated to?",
  "What’s the #1 thing you would never want your parents to find out about you?",
  "What was the worst sex you ever had?",
  "What’s the kinkiest thing you’ve ever done?",
  "Which of your exes would you still be willing to sleep with?",
  "What’s the biggest secret that you’re keeping from everyone in this room?",
  "What’s your magic number?",
  "What’s the biggest age difference you’ve had between yourself and a sexual partner?",
  "What’s the kinkiest sex toy you’ve ever used with a partner?",
  "What’s the most scandalous location you’ve had sex in?",
  "What’s the most disgusting habit you have?",
  "What’s the most embarrassing thing that’s ever happened to you during sex?",
  "What’s your biggest turn-on?",
  "What’s your biggest turn-off?",
  "How long has your longest dry spell been?",
  "What – if any – amount of money would you be willing to have sex with a stranger for?",
  "What’s the most embarrassing TV show that you watch?",
  "What’s the furthest you’ve gone sexually with a member of the same sex?",
  "Which sexual act are you best at?",
  "Which sexual act are you worst at?",
  "Are you more dominant or more submissive in bed?",
  "What’s the dirtiest thing a partner’s ever asked you to do?",
  "What’s the most illegal thing you’ve ever done?",
  "Where’s the most inappropriate place you’ve ever masturbated?",
  "What’s the most desperate thing you’ve ever done because you were horny?",
  "What’s your most outrageous sexual fantasy?",
  "What was the last thing you cried over?",
  "How many sex toys do you own?",
  "What’s the longest you’ve gone without showering?",
  "What’s the most embarrassing thing you’ve ever been caught doing?",
  "How often do you fake orgasms?",
  "What’s the hottest sex you’ve ever had?",
  "What is your biggest sexual regret?",
  "What’s the dirtiest sext you’ve ever sent?",
  "What’s something you’ve done while drunk that you would never do sober?",
  "What’s the closest you’ve ever come to cheating?",
  "Who’s the most scandalous person you’ve had sex with?",
  "How many of the people you’ve slept with did you meet online?",
  "What’s the least amount of time you’ve known someone for before sleeping with them?",
  "What’s the most bizarre sexual role-play you’ve ever participated in?",
];
